#ifndef DEFINE_H_INCLUDED
#define DEFINE_H_INCLUDED

#define NORMALSTATS 10
#define TABSIZERANDOM 100

#define ATTRIBUTPOINT 30
#define COMPETENCESPOINT 12

#define NBCOMPETENCEINIT 4
#define LIMITATTRIBUTSCREATION 18
#define LIMITHORSCLASS 2
#define LIMITCLASS 4


#endif